- hosts: live2
  tasks:
  - name: "Repository"
    yum_repository:
        name: "Docker"
        description: "Docker Repo"
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
        gpgcheck: "no"

  - name: "Installing docker package"
    package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present

  - name: "Starting docker"
    service:
        name: "docker"
        state: started
        enabled: yes

  - name: "Installing Python3"
    package:
        name: "python3"
        state: present

  - name: "Installing Docker SDK For Python"
    command: "pip3 install docker"

  - name: "Creating Folder And Copying File In Folder"
    file:
        path: "/datafile"
        state: directory

  - name: "Copying File From Local"
    copy:
        src: "rahul.html"
        dest: "/datafile/"

  - name: "Creating Container"
    docker_container:
        name: "webserver"
        image: "httpd"
        state: started
        exposed_ports:
        - "80"
        ports:
        - "1234:80"
        volumes:
        - /datafile:/usr/local/apache2/htdocs/
